### ISSUE TITLE
ClimateCoverData has no attribute 'outdoor_high'

### ISSUE THREAD

**Issue by miezie** [basbruss/adaptive-cover#271]
### What version of Adaptive Cover are you using?

1.4.0

### What version of Home Assistant are you using?

2024.7.4

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Logger: custom_components.adaptive_cover
Bron: helpers/update_coordinator.py:312
integratie: Adaptive Cover ([documentatie](https://github.com/basbruss/adaptive-cover), [problemen](https://github.com/basbruss/adaptive-cover/issues))
Eerst voorgekomen: 14:28:07 (50 gebeurtenissen)
Laatst gelogd: 14:30:06

Unexpected error fetching adaptive_cover data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_cover/coordinator.py", line 231, in _async_update_data
    self.climate_mode_data(options, cover_data)
  File "/config/custom_components/adaptive_cover/coordinator.py", line 585, in climate_mode_data
    self.climate_state = round(ClimateCoverState(cover_data, climate).get_state())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_cover/calculation.py", line 425, in get_state
    result = self.normal_type_cover()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_cover/calculation.py", line 353, in normal_type_cover
    return self.normal_with_presence()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_cover/calculation.py", line 361, in normal_with_presence
    if not self.climate_data.is_summer and (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_cover/calculation.py", line 309, in is_summer
    return self.get_current_temperature > self.temp_high and self.outdoor_high
                                                             ^^^^^^^^^^^^^^^^^
AttributeError: 'ClimateCoverData' object has no attribute 'outdoor_high'. Did you mean: 'outside_high'?

### Reproduction steps

1. Upgrade from previous release to new one via HACS
2.
3.
...

**Comment by basbruss** [comment]
Fixed with https://github.com/basbruss/adaptive-cover/releases/tag/v1.4.1
