### ISSUE TITLE
Failed to Setup

### ISSUE THREAD

**Issue by chknlil** [basbruss/adaptive-cover#323]
### What version of Adaptive Cover are you using?

1.4.4

### What version of Home Assistant are you using?

2024.10.3

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After install and configure, integration shows "failed to setup: Check the logs"

### Reproduction steps

1. Configure
2. Reload
3. Review Logs
...

### Diagnostics dump

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 8:26:44 AM (3 occurrences)
Last logged: 8:28:40 AM

Error setting up entry Vertical Blind Control for adaptive_cover
Error setting up entry Vertical test for adaptive_cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_cover/__init__.py", line 40, in async_setup_entry
    coordinator = AdaptiveDataUpdateCoordinator(hass)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_cover/coordinator.py", line 157, in __init__
    self.manager = AdaptiveCoverManager(self.manual_duration)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_cover/coordinator.py", line 787, in __init__
    self.reset_duration = dt.timedelta(**reset_duration)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: datetime.timedelta() argument after ** must be a mapping, not NoneType

**Comment by steakpowered** [comment]
I'm seeing the same issue.

**Comment by chknlil** [comment]
Issue may be resolved after the rollback for HA that was performed after updated to 1.4.5:  Will be testing further today.

https://github.com/basbruss/adaptive-cover/actions/runs/11499872619

**Comment by chknlil** [comment]
I believe this can be closed now, testing today showed it to be working after install/update and blinds working well!  TY!!!  Great project.
