### ISSUE TITLE
Unable to add new integration getting error

### ISSUE THREAD

**Issue by Diondk** [basbruss/adaptive-cover#81]
## System Information

version | core-2024.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.20-haos
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4636
Installed Version | 1.34.0
Stage | running
Available Repositories | 1410
Downloaded Repositories | 40
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | April 2, 2024 at 2:00 AM
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-14.ui.nabu.casa
certificate_status | ready
instance_id | 40bc7b67d1c5431387da8505a5808870
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 19.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.1), Terminal & SSH (9.10.0), Tesla HTTP Proxy (1.3.7)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 20
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 13, 2024 at 10:58 AM
-- | --
current_recorder_run | March 23, 2024 at 4:37 PM
estimated_db_size | 2454.54 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When creating a new integration i am getting the following error on the integration page after clicking ok.
![image](https://github.com/basbruss/adaptive-cover/assets/4394449/dcd74e77-6a58-4c83-af88-5f3889dca072)

While i have an entity configured:
![image](https://github.com/basbruss/adaptive-cover/assets/4394449/2eaabcd6-29d4-43ee-b212-af15ce66a292)

And the log files shows this:

`Unexpected error fetching adaptive_cover data: cannot access local variable 'climate_data' where it is not associated with a value
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_cover/coordinator.py", line 191, in _async_update_data
    "outside_temp": climate_data.outside_temperature,
                    ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'climate_data' where it is not associated with a value`

### Reproduction steps

1. create a new adaptive cover integration
2. Click submit
3. Integration is not loaded and shows the error.
...

**Comment by Diondk** [comment]
Fixed after reinstalling 0.5.1
